<?php

namespace App\Http\Controllers\QC\Extruder;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB;
use Log;
use App\Http\Controllers\HakAksesController;
use Exception;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

class VerifikasiSMController extends Controller
{
    public function index()
    {
        $access = (new HakAksesController)->HakAksesFiturMaster('QC');
        $listTypeMesin = DB::connection('ConnTestQC')
            ->select('EXEC SP_4451_List_Mesin_CL @Kode = ?', [1]);
        $listLokasi = DB::connection('ConnTestQC')
            ->table('Lokasi')
            ->select('idLokasi', 'nama_lokasi')
            ->get();
        // $filtered = array_values(array_filter($listTypeMesin, function ($item) {
        //     return in_array($item->IdType_Mesin, ['13', '17']);
        // }));
        // // dd($filtered);
        // usort($filtered, function ($a, $b) {
        //     return intval($a->IdType_Mesin) - intval($b->IdType_Mesin);
        // });
        // $listLokasi = collect($listLokasi)
        //     ->whereIn('idLokasi', [1])
        //     ->values();
        return view('QC.Extruder.VerifikasiSM', compact('access', 'listLokasi'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        // dd($request->all());
        $proses = $request->input('proses');
        $user_input = trim(Auth::user()->NomorUser);
        $idLaporan = $request->input('idLaporan');
        $keterangan = $request->input('keterangan');
        $hasilCheck = $request->input('hasilCheck');

        try {
            switch ($proses) {
                case 1:
                    // Cek apakah sudah ada keterangan
                    $result = DB::connection('ConnTestQC')
                        ->selectOne(
                            'EXEC SP_4451_VerifikasiSettingMesin 
                                @kode = ?,
                                @idLaporan = ?',
                            [
                                1,
                                $idLaporan,
                            ]
                        );

                    // Jika belum ada keterangan
                    if (!$result || $result->count <= 0) {
                        return response()->json([
                            'error' => 'Lakukan proses simpan keterangan dahulu sebelum verifikasi!'
                        ]);
                    }

                    // Jika sudah ada keterangan, lanjut proses verifikasi
                    DB::connection('ConnExtruder')
                        ->statement(
                            'EXEC SP_4451_GetDataLaporanProduksiExtruder 
                                @kode = ?,
                                @idLaporan = ?,
                                @user_input = ?',
                            [
                                5,
                                $idLaporan,
                                $user_input,
                            ]
                        );

                    return response()->json([
                        'message' => 'Data berhasil diverifikasi!'
                    ]);

                case 2:
                    // dd($request->all());
                    DB::connection('ConnExtruder')
                        ->statement(
                            'EXEC SP_4451_GetDataLaporanProduksiExtruder 
                        @kode = ?,
                        @idLaporan = ?,
                        @keterangan = ?,
                        @user_input = ?,
                        @c1B_status = ?,
                        @c1B_value = ?,
                        @c1C_status = ?,
                        @c1C_value = ?,
                        @c1D_status = ?,
                        @c1D_value = ?,
                        @c1E_status = ?,
                        @c1E_value = ?,
                        @c1F_status = ?,
                        @c1F_value = ?,
                        @c1G_status = ?,
                        @c1G_value = ?,
                        @c2B_status = ?,
                        @c2B_value = ?,
                        @c2C_status = ?,
                        @c2C_value = ?,
                        @c2D_status = ?,
                        @c2D_value = ?,
                        @c2E_status = ?,
                        @c2E_value = ?,
                        @c2F_status = ?,
                        @c2F_value = ?,
                        @c2G_status = ?,
                        @c2G_value = ?,
                        @c3B_status = ?,
                        @c3B_value = ?,
                        @c3C_status = ?,
                        @c3C_value = ?,
                        @c3D_status = ?,
                        @c3D_value = ?,
                        @c3E_status = ?,
                        @c3E_value = ?,
                        @c3F_status = ?,
                        @c3F_value = ?,
                        @c3G_status = ?,
                        @c3G_value = ?,
                        @c4B_status = ?,
                        @c4B_value = ?,
                        @c4C_status = ?,
                        @c4C_value = ?,
                        @c4D_status = ?,
                        @c4D_value = ?,
                        @c4E_status = ?,
                        @c4E_value = ?,
                        @c4F_status = ?,
                        @c4F_value = ?,
                        @c4G_status = ?,
                        @c4G_value = ?,
                        @c5B_status = ?,
                        @c5B_value = ?,
                        @c5C_status = ?,
                        @c5C_value = ?,
                        @c5D_status = ?,
                        @c5D_value = ?,
                        @c5E_status = ?,
                        @c5E_value = ?,
                        @c5F_status = ?,
                        @c5F_value = ?,
                        @c5G_status = ?,
                        @c5G_value = ?,
                        @c6B_status = ?,
                        @c6B_value = ?,
                        @c6C_status = ?,
                        @c6C_value = ?,
                        @c6D_status = ?,
                        @c6D_value = ?,
                        @c6E_status = ?,
                        @c6E_value = ?,
                        @c6F_status = ?,
                        @c6F_value = ?,
                        @c6G_status = ?,
                        @c6G_value = ?,
                        @c7B_status = ?,
                        @c7B_value = ?,
                        @c7C_status = ?,
                        @c7C_value = ?,
                        @c7D_status = ?,
                        @c7D_value = ?,
                        @c7E_status = ?,
                        @c7E_value = ?,
                        @c7F_status = ?,
                        @c7F_value = ?,
                        @c7G_status = ?,
                        @c7G_value = ?,
                        @c8B_status = ?,
                        @c8B_value = ?,
                        @c8C_status = ?,
                        @c8C_value = ?,
                        @c8D_status = ?,
                        @c8D_value = ?,
                        @c8E_status = ?,
                        @c8E_value = ?,
                        @c8F_status = ?,
                        @c8F_value = ?,
                        @c8G_status = ?,
                        @c8G_value = ?,
                        @flB_status = ?,
                        @flB_value = ?,
                        @flC_status = ?,
                        @flC_value = ?,
                        @flD_status = ?,
                        @flD_value = ?,
                        @flE_status = ?,
                        @flE_value = ?,
                        @flF_status = ?,
                        @flF_value = ?,
                        @flG_status = ?,
                        @flG_value = ?,
                        @scB_status = ?,
                        @scB_value = ?,
                        @scC_status = ?,
                        @scC_value = ?,
                        @scD_status = ?,
                        @scD_value = ?,
                        @scE_status = ?,
                        @scE_value = ?,
                        @scF_status = ?,
                        @scF_value = ?,
                        @scG_status = ?,
                        @scG_value = ?,
                        @jnB_status = ?,
                        @jnB_value = ?,
                        @jnC_status = ?,
                        @jnC_value = ?,
                        @jnD_status = ?,
                        @jnD_value = ?,
                        @jnE_status = ?,
                        @jnE_value = ?,
                        @jnF_status = ?,
                        @jnF_value = ?,
                        @jnG_status = ?,
                        @jnG_value = ?,
                        @d1B_status = ?,
                        @d1B_value = ?,
                        @d1C_status = ?,
                        @d1C_value = ?,
                        @d1D_status = ?,
                        @d1D_value = ?,
                        @d1E_status = ?,
                        @d1E_value = ?,
                        @d1F_status = ?,
                        @d1F_value = ?,
                        @d1G_status = ?,
                        @d1G_value = ?,
                        @d2B_status = ?,
                        @d2B_value = ?,
                        @d2C_status = ?,
                        @d2C_value = ?,
                        @d2D_status = ?,
                        @d2D_value = ?,
                        @d2E_status = ?,
                        @d2E_value = ?,
                        @d2F_status = ?,
                        @d2F_value = ?,
                        @d2G_status = ?,
                        @d2G_value = ?,
                        @d3B_status = ?,
                        @d3B_value = ?,
                        @d3C_status = ?,
                        @d3C_value = ?,
                        @d3D_status = ?,
                        @d3D_value = ?,
                        @d3E_status = ?,
                        @d3E_value = ?,
                        @d3F_status = ?,
                        @d3F_value = ?,
                        @d3G_status = ?,
                        @d3G_value = ?,
                        @d4B_status = ?,
                        @d4B_value = ?,
                        @d4C_status = ?,
                        @d4C_value = ?,
                        @d4D_status = ?,
                        @d4D_value = ?,
                        @d4E_status = ?,
                        @d4E_value = ?,
                        @d4F_status = ?,
                        @d4F_value = ?,
                        @d4G_status = ?,
                        @d4G_value = ?,
                        @d5B_status = ?,
                        @d5B_value = ?,
                        @d5C_status = ?,
                        @d5C_value = ?,
                        @d5D_status = ?,
                        @d5D_value = ?,
                        @d5E_status = ?,
                        @d5E_value = ?,
                        @d5F_status = ?,
                        @d5F_value = ?,
                        @d5G_status = ?,
                        @d5G_value = ?,
                        @d6B_status = ?,
                        @d6B_value = ?,
                        @d6C_status = ?,
                        @d6C_value = ?,
                        @d6D_status = ?,
                        @d6D_value = ?,
                        @d6E_status = ?,
                        @d6E_value = ?,
                        @d6F_status = ?,
                        @d6F_value = ?,
                        @d6G_status = ?,
                        @d6G_value = ?,
                        @srB_status = ?,
                        @srB_value = ?,
                        @srC_status = ?,
                        @srC_value = ?,
                        @srD_status = ?,
                        @srD_value = ?,
                        @srE_status = ?,
                        @srE_value = ?,
                        @srF_status = ?,
                        @srF_value = ?,
                        @srG_status = ?,
                        @srG_value = ?,
                        @mrB_status = ?,
                        @mrB_value = ?,
                        @mrC_status = ?,
                        @mrC_value = ?,
                        @mrD_status = ?,
                        @mrD_value = ?,
                        @mrE_status = ?,
                        @mrE_value = ?,
                        @mrF_status = ?,
                        @mrF_value = ?,
                        @mrG_status = ?,
                        @mrG_value = ?,
                        @mvB_status = ?,
                        @mvB_value = ?,
                        @mvC_status = ?,
                        @mvC_value = ?,
                        @mvD_status = ?,
                        @mvD_value = ?,
                        @mvE_status = ?,
                        @mvE_value = ?,
                        @mvF_status = ?,
                        @mvF_value = ?,
                        @mvG_status = ?,
                        @mvG_value = ?,
                        @mpp1B_status = ?,
                        @mpp1B_value = ?,
                        @mpp1C_status = ?,
                        @mpp1C_value = ?,
                        @mpp1D_status = ?,
                        @mpp1D_value = ?,
                        @mpp1E_status = ?,
                        @mpp1E_value = ?,
                        @mpp1F_status = ?,
                        @mpp1F_value = ?,
                        @mpp1G_status = ?,
                        @mpp1G_value = ?,
                        @mpp2B_status = ?,
                        @mpp2B_value = ?,
                        @mpp2C_status = ?,
                        @mpp2C_value = ?,
                        @mpp2D_status = ?,
                        @mpp2D_value = ?,
                        @mpp2E_status = ?,
                        @mpp2E_value = ?,
                        @mpp2F_status = ?,
                        @mpp2F_value = ?,
                        @mpp2G_status = ?,
                        @mpp2G_value = ?,
                        @qbB_status = ?,
                        @qbB_value = ?,
                        @qbC_status = ?,
                        @qbC_value = ?,
                        @qbD_status = ?,
                        @qbD_value = ?,
                        @qbE_status = ?,
                        @qbE_value = ?,
                        @qbF_status = ?,
                        @qbF_value = ?,
                        @qbG_status = ?,
                        @qbG_value = ?,
                        @fewB_status = ?,
                        @fewB_value = ?,
                        @fewC_status = ?,
                        @fewC_value = ?,
                        @fewD_status = ?,
                        @fewD_value = ?,
                        @fewE_status = ?,
                        @fewE_value = ?,
                        @fewF_status = ?,
                        @fewF_value = ?,
                        @fewG_status = ?,
                        @fewG_value = ?,
                        @swB_status = ?,
                        @swB_value = ?,
                        @swC_status = ?,
                        @swC_value = ?,
                        @swD_status = ?,
                        @swD_value = ?,
                        @swE_status = ?,
                        @swE_value = ?,
                        @swF_status = ?,
                        @swF_value = ?,
                        @swG_status = ?,
                        @swG_value = ?,
                        @noyB_status = ?,
                        @noyB_value = ?,
                        @noyC_status = ?,
                        @noyC_value = ?,
                        @noyD_status = ?,
                        @noyD_value = ?,
                        @noyE_status = ?,
                        @noyE_value = ?,
                        @noyF_status = ?,
                        @noyF_value = ?,
                        @noyG_status = ?,
                        @noyG_value = ?,
                        @wgB_status = ?,
                        @wgB_value = ?,
                        @wgC_status = ?,
                        @wgC_value = ?,
                        @wgD_status = ?,
                        @wgD_value = ?,
                        @wgE_status = ?,
                        @wgE_value = ?,
                        @wgF_status = ?,
                        @wgF_value = ?,
                        @wgG_status = ?,
                        @wgG_value = ?,
                        @rs1B_status = ?,
                        @rs1B_value = ?,
                        @rs1C_status = ?,
                        @rs1C_value = ?,
                        @rs1D_status = ?,
                        @rs1D_value = ?,
                        @rs1E_status = ?,
                        @rs1E_value = ?,
                        @rs1F_status = ?,
                        @rs1F_value = ?,
                        @rs1G_status = ?,
                        @rs1G_value = ?,
                        @rs2B_status = ?,
                        @rs2B_value = ?,
                        @rs2C_status = ?,
                        @rs2C_value = ?,
                        @rs2D_status = ?,
                        @rs2D_value = ?,
                        @rs2E_status = ?,
                        @rs2E_value = ?,
                        @rs2F_status = ?,
                        @rs2F_value = ?,
                        @rs2G_status = ?,
                        @rs2G_value = ?,
                        @rs3B_status = ?,
                        @rs3B_value = ?,
                        @rs3C_status = ?,
                        @rs3C_value = ?,
                        @rs3D_status = ?,
                        @rs3D_value = ?,
                        @rs3E_status = ?,
                        @rs3E_value = ?,
                        @rs3F_status = ?,
                        @rs3F_value = ?,
                        @rs3G_status = ?,
                        @rs3G_value = ?,
                        @strB_status = ?,
                        @strB_value = ?,
                        @strC_status = ?,
                        @strC_value = ?,
                        @strD_status = ?,
                        @strD_value = ?,
                        @strE_status = ?,
                        @strE_value = ?,
                        @strF_status = ?,
                        @strF_value = ?,
                        @strG_status = ?,
                        @strG_value = ?,
                        @rB_status = ?,
                        @rB_value = ?,
                        @rC_status = ?,
                        @rC_value = ?,
                        @rD_status = ?,
                        @rD_value = ?,
                        @rE_status = ?,
                        @rE_value = ?,
                        @rF_status = ?,
                        @rF_value = ?,
                        @rG_status = ?,
                        @rG_value = ?,
                        @uotB_status = ?,
                        @uotB_value = ?,
                        @uotC_status = ?,
                        @uotC_value = ?,
                        @uotD_status = ?,
                        @uotD_value = ?,
                        @uotE_status = ?,
                        @uotE_value = ?,
                        @uotF_status = ?,
                        @uotF_value = ?,
                        @uotG_status = ?,
                        @uotG_value = ?,
                        @lotB_status = ?,
                        @lotB_value = ?,
                        @lotC_status = ?,
                        @lotC_value = ?,
                        @lotD_status = ?,
                        @lotD_value = ?,
                        @lotE_status = ?,
                        @lotE_value = ?,
                        @lotF_status = ?,
                        @lotF_value = ?,
                        @lotG_status = ?,
                        @lotG_value = ?,
                        @at1B_status = ?,
                        @at1B_value = ?,
                        @at1C_status = ?,
                        @at1C_value = ?,
                        @at1D_status = ?,
                        @at1D_value = ?,
                        @at1E_status = ?,
                        @at1E_value = ?,
                        @at1F_status = ?,
                        @at1F_value = ?,
                        @at1G_status = ?,
                        @at1G_value = ?,
                        @at2B_status = ?,
                        @at2B_value = ?,
                        @at2C_status = ?,
                        @at2C_value = ?,
                        @at2D_status = ?,
                        @at2D_value = ?,
                        @at2E_status = ?,
                        @at2E_value = ?,
                        @at2F_status = ?,
                        @at2F_value = ?,
                        @at2G_status = ?,
                        @at2G_value = ?,
                        @at3B_status = ?,
                        @at3B_value = ?,
                        @at3C_status = ?,
                        @at3C_value = ?,
                        @at3D_status = ?,
                        @at3D_value = ?,
                        @at3E_status = ?,
                        @at3E_value = ?,
                        @at3F_status = ?,
                        @at3F_value = ?,
                        @at3G_status = ?,
                        @at3G_value = ?',
                            [
                                6,
                                $idLaporan,
                                $keterangan,
                                $user_input,
                                $hasilCheck['c1B']['status'] ?? null,
                                $hasilCheck['c1B']['value'] ?? null,
                                $hasilCheck['c1C']['status'] ?? null,
                                $hasilCheck['c1C']['value'] ?? null,
                                $hasilCheck['c1D']['status'] ?? null,
                                $hasilCheck['c1D']['value'] ?? null,
                                $hasilCheck['c1E']['status'] ?? null,
                                $hasilCheck['c1E']['value'] ?? null,
                                $hasilCheck['c1F']['status'] ?? null,
                                $hasilCheck['c1F']['value'] ?? null,
                                $hasilCheck['c1G']['status'] ?? null,
                                $hasilCheck['c1G']['value'] ?? null,
                                $hasilCheck['c2B']['status'] ?? null,
                                $hasilCheck['c2B']['value'] ?? null,
                                $hasilCheck['c2C']['status'] ?? null,
                                $hasilCheck['c2C']['value'] ?? null,
                                $hasilCheck['c2D']['status'] ?? null,
                                $hasilCheck['c2D']['value'] ?? null,
                                $hasilCheck['c2E']['status'] ?? null,
                                $hasilCheck['c2E']['value'] ?? null,
                                $hasilCheck['c2F']['status'] ?? null,
                                $hasilCheck['c2F']['value'] ?? null,
                                $hasilCheck['c2G']['status'] ?? null,
                                $hasilCheck['c2G']['value'] ?? null,
                                $hasilCheck['c3B']['status'] ?? null,
                                $hasilCheck['c3B']['value'] ?? null,
                                $hasilCheck['c3C']['status'] ?? null,
                                $hasilCheck['c3C']['value'] ?? null,
                                $hasilCheck['c3D']['status'] ?? null,
                                $hasilCheck['c3D']['value'] ?? null,
                                $hasilCheck['c3E']['status'] ?? null,
                                $hasilCheck['c3E']['value'] ?? null,
                                $hasilCheck['c3F']['status'] ?? null,
                                $hasilCheck['c3F']['value'] ?? null,
                                $hasilCheck['c3G']['status'] ?? null,
                                $hasilCheck['c3G']['value'] ?? null,
                                $hasilCheck['c4B']['status'] ?? null,
                                $hasilCheck['c4B']['value'] ?? null,
                                $hasilCheck['c4C']['status'] ?? null,
                                $hasilCheck['c4C']['value'] ?? null,
                                $hasilCheck['c4D']['status'] ?? null,
                                $hasilCheck['c4D']['value'] ?? null,
                                $hasilCheck['c4E']['status'] ?? null,
                                $hasilCheck['c4E']['value'] ?? null,
                                $hasilCheck['c4F']['status'] ?? null,
                                $hasilCheck['c4F']['value'] ?? null,
                                $hasilCheck['c4G']['status'] ?? null,
                                $hasilCheck['c4G']['value'] ?? null,
                                $hasilCheck['c5B']['status'] ?? null,
                                $hasilCheck['c5B']['value'] ?? null,
                                $hasilCheck['c5C']['status'] ?? null,
                                $hasilCheck['c5C']['value'] ?? null,
                                $hasilCheck['c5D']['status'] ?? null,
                                $hasilCheck['c5D']['value'] ?? null,
                                $hasilCheck['c5E']['status'] ?? null,
                                $hasilCheck['c5E']['value'] ?? null,
                                $hasilCheck['c5F']['status'] ?? null,
                                $hasilCheck['c5F']['value'] ?? null,
                                $hasilCheck['c5G']['status'] ?? null,
                                $hasilCheck['c5G']['value'] ?? null,
                                $hasilCheck['c6B']['status'] ?? null,
                                $hasilCheck['c6B']['value'] ?? null,
                                $hasilCheck['c6C']['status'] ?? null,
                                $hasilCheck['c6C']['value'] ?? null,
                                $hasilCheck['c6D']['status'] ?? null,
                                $hasilCheck['c6D']['value'] ?? null,
                                $hasilCheck['c6E']['status'] ?? null,
                                $hasilCheck['c6E']['value'] ?? null,
                                $hasilCheck['c6F']['status'] ?? null,
                                $hasilCheck['c6F']['value'] ?? null,
                                $hasilCheck['c6G']['status'] ?? null,
                                $hasilCheck['c6G']['value'] ?? null,
                                $hasilCheck['c7B']['status'] ?? null,
                                $hasilCheck['c7B']['value'] ?? null,
                                $hasilCheck['c7C']['status'] ?? null,
                                $hasilCheck['c7C']['value'] ?? null,
                                $hasilCheck['c7D']['status'] ?? null,
                                $hasilCheck['c7D']['value'] ?? null,
                                $hasilCheck['c7E']['status'] ?? null,
                                $hasilCheck['c7E']['value'] ?? null,
                                $hasilCheck['c7F']['status'] ?? null,
                                $hasilCheck['c7F']['value'] ?? null,
                                $hasilCheck['c7G']['status'] ?? null,
                                $hasilCheck['c7G']['value'] ?? null,
                                $hasilCheck['c8B']['status'] ?? null,
                                $hasilCheck['c8B']['value'] ?? null,
                                $hasilCheck['c8C']['status'] ?? null,
                                $hasilCheck['c8C']['value'] ?? null,
                                $hasilCheck['c8D']['status'] ?? null,
                                $hasilCheck['c8D']['value'] ?? null,
                                $hasilCheck['c8E']['status'] ?? null,
                                $hasilCheck['c8E']['value'] ?? null,
                                $hasilCheck['c8F']['status'] ?? null,
                                $hasilCheck['c8F']['value'] ?? null,
                                $hasilCheck['c8G']['status'] ?? null,
                                $hasilCheck['c8G']['value'] ?? null,
                                $hasilCheck['flB']['status'] ?? null,
                                $hasilCheck['flB']['value'] ?? null,
                                $hasilCheck['flC']['status'] ?? null,
                                $hasilCheck['flC']['value'] ?? null,
                                $hasilCheck['flD']['status'] ?? null,
                                $hasilCheck['flD']['value'] ?? null,
                                $hasilCheck['flE']['status'] ?? null,
                                $hasilCheck['flE']['value'] ?? null,
                                $hasilCheck['flF']['status'] ?? null,
                                $hasilCheck['flF']['value'] ?? null,
                                $hasilCheck['flG']['status'] ?? null,
                                $hasilCheck['flG']['value'] ?? null,
                                $hasilCheck['scB']['status'] ?? null,
                                $hasilCheck['scB']['value'] ?? null,
                                $hasilCheck['scC']['status'] ?? null,
                                $hasilCheck['scC']['value'] ?? null,
                                $hasilCheck['scD']['status'] ?? null,
                                $hasilCheck['scD']['value'] ?? null,
                                $hasilCheck['scE']['status'] ?? null,
                                $hasilCheck['scE']['value'] ?? null,
                                $hasilCheck['scF']['status'] ?? null,
                                $hasilCheck['scF']['value'] ?? null,
                                $hasilCheck['scG']['status'] ?? null,
                                $hasilCheck['scG']['value'] ?? null,
                                $hasilCheck['jnB']['status'] ?? null,
                                $hasilCheck['jnB']['value'] ?? null,
                                $hasilCheck['jnC']['status'] ?? null,
                                $hasilCheck['jnC']['value'] ?? null,
                                $hasilCheck['jnD']['status'] ?? null,
                                $hasilCheck['jnD']['value'] ?? null,
                                $hasilCheck['jnE']['status'] ?? null,
                                $hasilCheck['jnE']['value'] ?? null,
                                $hasilCheck['jnF']['status'] ?? null,
                                $hasilCheck['jnF']['value'] ?? null,
                                $hasilCheck['jnG']['status'] ?? null,
                                $hasilCheck['jnG']['value'] ?? null,
                                $hasilCheck['d1B']['status'] ?? null,
                                $hasilCheck['d1B']['value'] ?? null,
                                $hasilCheck['d1C']['status'] ?? null,
                                $hasilCheck['d1C']['value'] ?? null,
                                $hasilCheck['d1D']['status'] ?? null,
                                $hasilCheck['d1D']['value'] ?? null,
                                $hasilCheck['d1E']['status'] ?? null,
                                $hasilCheck['d1E']['value'] ?? null,
                                $hasilCheck['d1F']['status'] ?? null,
                                $hasilCheck['d1F']['value'] ?? null,
                                $hasilCheck['d1G']['status'] ?? null,
                                $hasilCheck['d1G']['value'] ?? null,
                                $hasilCheck['d2B']['status'] ?? null,
                                $hasilCheck['d2B']['value'] ?? null,
                                $hasilCheck['d2C']['status'] ?? null,
                                $hasilCheck['d2C']['value'] ?? null,
                                $hasilCheck['d2D']['status'] ?? null,
                                $hasilCheck['d2D']['value'] ?? null,
                                $hasilCheck['d2E']['status'] ?? null,
                                $hasilCheck['d2E']['value'] ?? null,
                                $hasilCheck['d2F']['status'] ?? null,
                                $hasilCheck['d2F']['value'] ?? null,
                                $hasilCheck['d2G']['status'] ?? null,
                                $hasilCheck['d2G']['value'] ?? null,
                                $hasilCheck['d3B']['status'] ?? null,
                                $hasilCheck['d3B']['value'] ?? null,
                                $hasilCheck['d3C']['status'] ?? null,
                                $hasilCheck['d3C']['value'] ?? null,
                                $hasilCheck['d3D']['status'] ?? null,
                                $hasilCheck['d3D']['value'] ?? null,
                                $hasilCheck['d3E']['status'] ?? null,
                                $hasilCheck['d3E']['value'] ?? null,
                                $hasilCheck['d3F']['status'] ?? null,
                                $hasilCheck['d3F']['value'] ?? null,
                                $hasilCheck['d3G']['status'] ?? null,
                                $hasilCheck['d3G']['value'] ?? null,
                                $hasilCheck['d4B']['status'] ?? null,
                                $hasilCheck['d4B']['value'] ?? null,
                                $hasilCheck['d4C']['status'] ?? null,
                                $hasilCheck['d4C']['value'] ?? null,
                                $hasilCheck['d4D']['status'] ?? null,
                                $hasilCheck['d4D']['value'] ?? null,
                                $hasilCheck['d4E']['status'] ?? null,
                                $hasilCheck['d4E']['value'] ?? null,
                                $hasilCheck['d4F']['status'] ?? null,
                                $hasilCheck['d4F']['value'] ?? null,
                                $hasilCheck['d4G']['status'] ?? null,
                                $hasilCheck['d4G']['value'] ?? null,
                                $hasilCheck['d5B']['status'] ?? null,
                                $hasilCheck['d5B']['value'] ?? null,
                                $hasilCheck['d5C']['status'] ?? null,
                                $hasilCheck['d5C']['value'] ?? null,
                                $hasilCheck['d5D']['status'] ?? null,
                                $hasilCheck['d5D']['value'] ?? null,
                                $hasilCheck['d5E']['status'] ?? null,
                                $hasilCheck['d5E']['value'] ?? null,
                                $hasilCheck['d5F']['status'] ?? null,
                                $hasilCheck['d5F']['value'] ?? null,
                                $hasilCheck['d5G']['status'] ?? null,
                                $hasilCheck['d5G']['value'] ?? null,
                                $hasilCheck['d6B']['status'] ?? null,
                                $hasilCheck['d6B']['value'] ?? null,
                                $hasilCheck['d6C']['status'] ?? null,
                                $hasilCheck['d6C']['value'] ?? null,
                                $hasilCheck['d6D']['status'] ?? null,
                                $hasilCheck['d6D']['value'] ?? null,
                                $hasilCheck['d6E']['status'] ?? null,
                                $hasilCheck['d6E']['value'] ?? null,
                                $hasilCheck['d6F']['status'] ?? null,
                                $hasilCheck['d6F']['value'] ?? null,
                                $hasilCheck['d6G']['status'] ?? null,
                                $hasilCheck['d6G']['value'] ?? null,
                                $hasilCheck['srB']['status'] ?? null,
                                $hasilCheck['srB']['value'] ?? null,
                                $hasilCheck['srC']['status'] ?? null,
                                $hasilCheck['srC']['value'] ?? null,
                                $hasilCheck['srD']['status'] ?? null,
                                $hasilCheck['srD']['value'] ?? null,
                                $hasilCheck['srE']['status'] ?? null,
                                $hasilCheck['srE']['value'] ?? null,
                                $hasilCheck['srF']['status'] ?? null,
                                $hasilCheck['srF']['value'] ?? null,
                                $hasilCheck['srG']['status'] ?? null,
                                $hasilCheck['srG']['value'] ?? null,
                                $hasilCheck['mrB']['status'] ?? null,
                                $hasilCheck['mrB']['value'] ?? null,
                                $hasilCheck['mrC']['status'] ?? null,
                                $hasilCheck['mrC']['value'] ?? null,
                                $hasilCheck['mrD']['status'] ?? null,
                                $hasilCheck['mrD']['value'] ?? null,
                                $hasilCheck['mrE']['status'] ?? null,
                                $hasilCheck['mrE']['value'] ?? null,
                                $hasilCheck['mrF']['status'] ?? null,
                                $hasilCheck['mrF']['value'] ?? null,
                                $hasilCheck['mrG']['status'] ?? null,
                                $hasilCheck['mrG']['value'] ?? null,
                                $hasilCheck['mvB']['status'] ?? null,
                                $hasilCheck['mvB']['value'] ?? null,
                                $hasilCheck['mvC']['status'] ?? null,
                                $hasilCheck['mvC']['value'] ?? null,
                                $hasilCheck['mvD']['status'] ?? null,
                                $hasilCheck['mvD']['value'] ?? null,
                                $hasilCheck['mvE']['status'] ?? null,
                                $hasilCheck['mvE']['value'] ?? null,
                                $hasilCheck['mvF']['status'] ?? null,
                                $hasilCheck['mvF']['value'] ?? null,
                                $hasilCheck['mvG']['status'] ?? null,
                                $hasilCheck['mvG']['value'] ?? null,
                                $hasilCheck['mpp1B']['status'] ?? null,
                                $hasilCheck['mpp1B']['value'] ?? null,
                                $hasilCheck['mpp1C']['status'] ?? null,
                                $hasilCheck['mpp1C']['value'] ?? null,
                                $hasilCheck['mpp1D']['status'] ?? null,
                                $hasilCheck['mpp1D']['value'] ?? null,
                                $hasilCheck['mpp1E']['status'] ?? null,
                                $hasilCheck['mpp1E']['value'] ?? null,
                                $hasilCheck['mpp1F']['status'] ?? null,
                                $hasilCheck['mpp1F']['value'] ?? null,
                                $hasilCheck['mpp1G']['status'] ?? null,
                                $hasilCheck['mpp1G']['value'] ?? null,
                                $hasilCheck['mpp2B']['status'] ?? null,
                                $hasilCheck['mpp2B']['value'] ?? null,
                                $hasilCheck['mpp2C']['status'] ?? null,
                                $hasilCheck['mpp2C']['value'] ?? null,
                                $hasilCheck['mpp2D']['status'] ?? null,
                                $hasilCheck['mpp2D']['value'] ?? null,
                                $hasilCheck['mpp2E']['status'] ?? null,
                                $hasilCheck['mpp2E']['value'] ?? null,
                                $hasilCheck['mpp2F']['status'] ?? null,
                                $hasilCheck['mpp2F']['value'] ?? null,
                                $hasilCheck['mpp2G']['status'] ?? null,
                                $hasilCheck['mpp2G']['value'] ?? null,
                                $hasilCheck['qbB']['status'] ?? null,
                                $hasilCheck['qbB']['value'] ?? null,
                                $hasilCheck['qbC']['status'] ?? null,
                                $hasilCheck['qbC']['value'] ?? null,
                                $hasilCheck['qbD']['status'] ?? null,
                                $hasilCheck['qbD']['value'] ?? null,
                                $hasilCheck['qbE']['status'] ?? null,
                                $hasilCheck['qbE']['value'] ?? null,
                                $hasilCheck['qbF']['status'] ?? null,
                                $hasilCheck['qbF']['value'] ?? null,
                                $hasilCheck['qbG']['status'] ?? null,
                                $hasilCheck['qbG']['value'] ?? null,
                                $hasilCheck['fewB']['status'] ?? null,
                                $hasilCheck['fewB']['value'] ?? null,
                                $hasilCheck['fewC']['status'] ?? null,
                                $hasilCheck['fewC']['value'] ?? null,
                                $hasilCheck['fewD']['status'] ?? null,
                                $hasilCheck['fewD']['value'] ?? null,
                                $hasilCheck['fewE']['status'] ?? null,
                                $hasilCheck['fewE']['value'] ?? null,
                                $hasilCheck['fewF']['status'] ?? null,
                                $hasilCheck['fewF']['value'] ?? null,
                                $hasilCheck['fewG']['status'] ?? null,
                                $hasilCheck['fewG']['value'] ?? null,
                                $hasilCheck['swB']['status'] ?? null,
                                $hasilCheck['swB']['value'] ?? null,
                                $hasilCheck['swC']['status'] ?? null,
                                $hasilCheck['swC']['value'] ?? null,
                                $hasilCheck['swD']['status'] ?? null,
                                $hasilCheck['swD']['value'] ?? null,
                                $hasilCheck['swE']['status'] ?? null,
                                $hasilCheck['swE']['value'] ?? null,
                                $hasilCheck['swF']['status'] ?? null,
                                $hasilCheck['swF']['value'] ?? null,
                                $hasilCheck['swG']['status'] ?? null,
                                $hasilCheck['swG']['value'] ?? null,
                                $hasilCheck['noyB']['status'] ?? null,
                                $hasilCheck['noyB']['value'] ?? null,
                                $hasilCheck['noyC']['status'] ?? null,
                                $hasilCheck['noyC']['value'] ?? null,
                                $hasilCheck['noyD']['status'] ?? null,
                                $hasilCheck['noyD']['value'] ?? null,
                                $hasilCheck['noyE']['status'] ?? null,
                                $hasilCheck['noyE']['value'] ?? null,
                                $hasilCheck['noyF']['status'] ?? null,
                                $hasilCheck['noyF']['value'] ?? null,
                                $hasilCheck['noyG']['status'] ?? null,
                                $hasilCheck['noyG']['value'] ?? null,
                                $hasilCheck['wgB']['status'] ?? null,
                                $hasilCheck['wgB']['value'] ?? null,
                                $hasilCheck['wgC']['status'] ?? null,
                                $hasilCheck['wgC']['value'] ?? null,
                                $hasilCheck['wgD']['status'] ?? null,
                                $hasilCheck['wgD']['value'] ?? null,
                                $hasilCheck['wgE']['status'] ?? null,
                                $hasilCheck['wgE']['value'] ?? null,
                                $hasilCheck['wgF']['status'] ?? null,
                                $hasilCheck['wgF']['value'] ?? null,
                                $hasilCheck['wgG']['status'] ?? null,
                                $hasilCheck['wgG']['value'] ?? null,
                                $hasilCheck['rs1B']['status'] ?? null,
                                $hasilCheck['rs1B']['value'] ?? null,
                                $hasilCheck['rs1C']['status'] ?? null,
                                $hasilCheck['rs1C']['value'] ?? null,
                                $hasilCheck['rs1D']['status'] ?? null,
                                $hasilCheck['rs1D']['value'] ?? null,
                                $hasilCheck['rs1E']['status'] ?? null,
                                $hasilCheck['rs1E']['value'] ?? null,
                                $hasilCheck['rs1F']['status'] ?? null,
                                $hasilCheck['rs1F']['value'] ?? null,
                                $hasilCheck['rs1G']['status'] ?? null,
                                $hasilCheck['rs1G']['value'] ?? null,
                                $hasilCheck['rs2B']['status'] ?? null,
                                $hasilCheck['rs2B']['value'] ?? null,
                                $hasilCheck['rs2C']['status'] ?? null,
                                $hasilCheck['rs2C']['value'] ?? null,
                                $hasilCheck['rs2D']['status'] ?? null,
                                $hasilCheck['rs2D']['value'] ?? null,
                                $hasilCheck['rs2E']['status'] ?? null,
                                $hasilCheck['rs2E']['value'] ?? null,
                                $hasilCheck['rs2F']['status'] ?? null,
                                $hasilCheck['rs2F']['value'] ?? null,
                                $hasilCheck['rs2G']['status'] ?? null,
                                $hasilCheck['rs2G']['value'] ?? null,
                                $hasilCheck['rs3B']['status'] ?? null,
                                $hasilCheck['rs3B']['value'] ?? null,
                                $hasilCheck['rs3C']['status'] ?? null,
                                $hasilCheck['rs3C']['value'] ?? null,
                                $hasilCheck['rs3D']['status'] ?? null,
                                $hasilCheck['rs3D']['value'] ?? null,
                                $hasilCheck['rs3E']['status'] ?? null,
                                $hasilCheck['rs3E']['value'] ?? null,
                                $hasilCheck['rs3F']['status'] ?? null,
                                $hasilCheck['rs3F']['value'] ?? null,
                                $hasilCheck['rs3G']['status'] ?? null,
                                $hasilCheck['rs3G']['value'] ?? null,
                                $hasilCheck['strB']['status'] ?? null,
                                $hasilCheck['strB']['value'] ?? null,
                                $hasilCheck['strC']['status'] ?? null,
                                $hasilCheck['strC']['value'] ?? null,
                                $hasilCheck['strD']['status'] ?? null,
                                $hasilCheck['strD']['value'] ?? null,
                                $hasilCheck['strE']['status'] ?? null,
                                $hasilCheck['strE']['value'] ?? null,
                                $hasilCheck['strF']['status'] ?? null,
                                $hasilCheck['strF']['value'] ?? null,
                                $hasilCheck['strG']['status'] ?? null,
                                $hasilCheck['strG']['value'] ?? null,
                                $hasilCheck['rB']['status'] ?? null,
                                $hasilCheck['rB']['value'] ?? null,
                                $hasilCheck['rC']['status'] ?? null,
                                $hasilCheck['rC']['value'] ?? null,
                                $hasilCheck['rD']['status'] ?? null,
                                $hasilCheck['rD']['value'] ?? null,
                                $hasilCheck['rE']['status'] ?? null,
                                $hasilCheck['rE']['value'] ?? null,
                                $hasilCheck['rF']['status'] ?? null,
                                $hasilCheck['rF']['value'] ?? null,
                                $hasilCheck['rG']['status'] ?? null,
                                $hasilCheck['rG']['value'] ?? null,
                                $hasilCheck['uotB']['status'] ?? null,
                                $hasilCheck['uotB']['value'] ?? null,
                                $hasilCheck['uotC']['status'] ?? null,
                                $hasilCheck['uotC']['value'] ?? null,
                                $hasilCheck['uotD']['status'] ?? null,
                                $hasilCheck['uotD']['value'] ?? null,
                                $hasilCheck['uotE']['status'] ?? null,
                                $hasilCheck['uotE']['value'] ?? null,
                                $hasilCheck['uotF']['status'] ?? null,
                                $hasilCheck['uotF']['value'] ?? null,
                                $hasilCheck['uotG']['status'] ?? null,
                                $hasilCheck['uotG']['value'] ?? null,
                                $hasilCheck['lotB']['status'] ?? null,
                                $hasilCheck['lotB']['value'] ?? null,
                                $hasilCheck['lotC']['status'] ?? null,
                                $hasilCheck['lotC']['value'] ?? null,
                                $hasilCheck['lotD']['status'] ?? null,
                                $hasilCheck['lotD']['value'] ?? null,
                                $hasilCheck['lotE']['status'] ?? null,
                                $hasilCheck['lotE']['value'] ?? null,
                                $hasilCheck['lotF']['status'] ?? null,
                                $hasilCheck['lotF']['value'] ?? null,
                                $hasilCheck['lotG']['status'] ?? null,
                                $hasilCheck['lotG']['value'] ?? null,
                                $hasilCheck['at1B']['status'] ?? null,
                                $hasilCheck['at1B']['value'] ?? null,
                                $hasilCheck['at1C']['status'] ?? null,
                                $hasilCheck['at1C']['value'] ?? null,
                                $hasilCheck['at1D']['status'] ?? null,
                                $hasilCheck['at1D']['value'] ?? null,
                                $hasilCheck['at1E']['status'] ?? null,
                                $hasilCheck['at1E']['value'] ?? null,
                                $hasilCheck['at1F']['status'] ?? null,
                                $hasilCheck['at1F']['value'] ?? null,
                                $hasilCheck['at1G']['status'] ?? null,
                                $hasilCheck['at1G']['value'] ?? null,
                                $hasilCheck['at2B']['status'] ?? null,
                                $hasilCheck['at2B']['value'] ?? null,
                                $hasilCheck['at2C']['status'] ?? null,
                                $hasilCheck['at2C']['value'] ?? null,
                                $hasilCheck['at2D']['status'] ?? null,
                                $hasilCheck['at2D']['value'] ?? null,
                                $hasilCheck['at2E']['status'] ?? null,
                                $hasilCheck['at2E']['value'] ?? null,
                                $hasilCheck['at2F']['status'] ?? null,
                                $hasilCheck['at2F']['value'] ?? null,
                                $hasilCheck['at2G']['status'] ?? null,
                                $hasilCheck['at2G']['value'] ?? null,
                                $hasilCheck['at3B']['status'] ?? null,
                                $hasilCheck['at3B']['value'] ?? null,
                                $hasilCheck['at3C']['status'] ?? null,
                                $hasilCheck['at3C']['value'] ?? null,
                                $hasilCheck['at3D']['status'] ?? null,
                                $hasilCheck['at3D']['value'] ?? null,
                                $hasilCheck['at3E']['status'] ?? null,
                                $hasilCheck['at3E']['value'] ?? null,
                                $hasilCheck['at3F']['status'] ?? null,
                                $hasilCheck['at3F']['value'] ?? null,
                                $hasilCheck['at3G']['status'] ?? null,
                                $hasilCheck['at3G']['value'] ?? null,
                            ]
                        );

                    return response()->json(['message' => 'Keterangan berhasil diupdate!']);

                case 3:
                    DB::connection('ConnExtruder')
                        ->statement(
                            'EXEC SP_4451_GetDataLaporanProduksiExtruder 
                        @kode = ?,
                        @idLaporan = ?,
                        @keterangan = ?,
                        @user_input = ?,
                        @bz1B_status = ?,
                        @bz1B_value = ?,
                        @bz1D_status = ?,
                        @bz1D_value = ?,
                        @bz1F_status = ?,
                        @bz1F_value = ?,
                        @bz2B_status = ?,
                        @bz2B_value = ?,
                        @bz2D_status = ?,
                        @bz2D_value = ?,
                        @bz2F_status = ?,
                        @bz2F_value = ?,
                        @bz3B_status = ?,
                        @bz3B_value = ?,
                        @bz3D_status = ?,
                        @bz3D_value = ?,
                        @bz3F_status = ?,
                        @bz3F_value = ?,
                        @bz4B_status = ?,
                        @bz4B_value = ?,
                        @bz4D_status = ?,
                        @bz4D_value = ?,
                        @bz4F_status = ?,
                        @bz4F_value = ?,
                        @bz5B_status = ?,
                        @bz5B_value = ?,
                        @bz5D_status = ?,
                        @bz5D_value = ?,
                        @bz5F_status = ?,
                        @bz5F_value = ?,
                        @bz6B_status = ?,
                        @bz6B_value = ?,
                        @bz6D_status = ?,
                        @bz6D_value = ?,
                        @bz6F_status = ?,
                        @bz6F_value = ?,
                        @scB_status = ?,
                        @scB_value = ?,
                        @scD_status = ?,
                        @scD_value = ?,
                        @scF_status = ?,
                        @scF_value = ?,
                        @mpB_status = ?,
                        @mpB_value = ?,
                        @mpD_status = ?,
                        @mpD_value = ?,
                        @mpF_status = ?,
                        @mpF_value = ?,
                        @ad1B_status = ?,
                        @ad1B_value = ?,
                        @ad1D_status = ?,
                        @ad1D_value = ?,
                        @ad1F_status = ?,
                        @ad1F_value = ?,
                        @ad2B_status = ?,
                        @ad2B_value = ?,
                        @ad2D_status = ?,
                        @ad2D_value = ?,
                        @ad2F_status = ?,
                        @ad2F_value = ?,
                        @wpheB_status = ?,
                        @wpheB_value = ?,
                        @wpheD_status = ?,
                        @wpheD_value = ?,
                        @wpheF_status = ?,
                        @wpheF_value = ?,
                        @ipheB_status = ?,
                        @ipheB_value = ?,
                        @ipheD_status = ?,
                        @ipheD_value = ?,
                        @ipheF_status = ?,
                        @ipheF_value = ?,
                        @mtB_status = ?,
                        @mtB_value = ?,
                        @mtD_status = ?,
                        @mtD_value = ?,
                        @mtF_status = ?,
                        @mtF_value = ?,
                        @dz1B_status = ?,
                        @dz1B_value = ?,
                        @dz1D_status = ?,
                        @dz1D_value = ?,
                        @dz1F_status = ?,
                        @dz1F_value = ?,
                        @dz2B_status = ?,
                        @dz2B_value = ?,
                        @dz2D_status = ?,
                        @dz2D_value = ?,
                        @dz2F_status = ?,
                        @dz2F_value = ?,
                        @dz3B_status = ?,
                        @dz3B_value = ?,
                        @dz3D_status = ?,
                        @dz3D_value = ?,
                        @dz3F_status = ?,
                        @dz3F_value = ?,
                        @dz4B_status = ?,
                        @dz4B_value = ?,
                        @dz4D_status = ?,
                        @dz4D_value = ?,
                        @dz4F_status = ?,
                        @dz4F_value = ?,
                        @dz5B_status = ?,
                        @dz5B_value = ?,
                        @dz5D_status = ?,
                        @dz5D_value = ?,
                        @dz5F_status = ?,
                        @dz5F_value = ?,
                        @haoB_status = ?,
                        @haoB_value = ?,
                        @haoD_status = ?,
                        @haoD_value = ?,
                        @haoF_status = ?,
                        @haoF_value = ?,
                        @unitB_status = ?,
                        @unitB_value = ?,
                        @unitD_status = ?,
                        @unitD_value = ?,
                        @unitF_status = ?,
                        @unitF_value = ?,
                        @mp2B_status = ?,
                        @mp2B_value = ?,
                        @mp2D_status = ?,
                        @mp2D_value = ?,
                        @mp2F_status = ?,
                        @mp2F_value = ?,
                        @extB_status = ?,
                        @extB_value = ?,
                        @extD_status = ?,
                        @extD_value = ?,
                        @extF_status = ?,
                        @extF_value = ?,
                        @niprB_status = ?,
                        @niprB_value = ?,
                        @niprD_status = ?,
                        @niprD_value = ?,
                        @niprF_status = ?,
                        @niprF_value = ?,
                        @trB_status = ?,
                        @trB_value = ?,
                        @trD_status = ?,
                        @trD_value = ?,
                        @trF_status = ?,
                        @trF_value = ?,
                        @huB_status = ?,
                        @huB_value = ?,
                        @huD_status = ?,
                        @huD_value = ?,
                        @huF_status = ?,
                        @huF_value = ?,
                        @isuB_status = ?,
                        @isuB_value = ?,
                        @isuD_status = ?,
                        @isuD_value = ?,
                        @isuF_status = ?,
                        @isuF_value = ?,
                        @suB_status = ?,
                        @suB_value = ?,
                        @suD_status = ?,
                        @suD_value = ?,
                        @suF_status = ?,
                        @suF_value = ?,
                        @pauB_status = ?,
                        @pauB_value = ?,
                        @pauD_status = ?,
                        @pauD_value = ?,
                        @pauF_status = ?,
                        @pauF_value = ?,
                        @auB_status = ?,
                        @auB_value = ?,
                        @auD_status = ?,
                        @auD_value = ?,
                        @auF_status = ?,
                        @auF_value = ?,
                        @wgB_status = ?,
                        @wgB_value = ?,
                        @wgD_status = ?,
                        @wgD_value = ?,
                        @wgF_status = ?,
                        @wgF_value = ?,
                        @fewB_status = ?,
                        @fewB_value = ?,
                        @fewD_status = ?,
                        @fewD_value = ?,
                        @fewF_status = ?,
                        @fewF_value = ?,
                        @noyB_status = ?,
                        @noyB_value = ?,
                        @noyD_status = ?,
                        @noyD_value = ?,
                        @noyF_status = ?,
                        @noyF_value = ?,
                        @swB_status = ?,
                        @swB_value = ?,
                        @swD_status = ?,
                        @swD_value = ?,
                        @swF_status = ?,
                        @swF_value = ?,
                        @totrB_status = ?,
                        @totrB_value = ?,
                        @totrD_status = ?,
                        @totrD_value = ?,
                        @totrF_status = ?,
                        @totrF_value = ?,
                        @relaxB_status = ?,
                        @relaxB_value = ?,
                        @relaxD_status = ?,
                        @relaxD_value = ?,
                        @relaxF_status = ?,
                        @relaxF_value = ?,
                        @tp2B_status = ?,
                        @tp2B_value = ?,
                        @tp2D_status = ?,
                        @tp2D_value = ?,
                        @tp2F_status = ?,
                        @tp2F_value = ?,
                        @tp1B_status = ?,
                        @tp1B_value = ?,
                        @tp1D_status = ?,
                        @tp1D_value = ?,
                        @tp1F_status = ?,
                        @tp1F_value = ?,
                        @tp3B_status = ?,
                        @tp3B_value = ?,
                        @tp3D_status = ?,
                        @tp3D_value = ?,
                        @tp3F_status = ?,
                        @tp3F_value = ?,
                        @at1B_status = ?,
                        @at1B_value = ?,
                        @at1D_status = ?,
                        @at1D_value = ?,
                        @at1F_status = ?,
                        @at1F_value = ?,
                        @at2B_status = ?,
                        @at2B_value = ?,
                        @at2D_status = ?,
                        @at2D_value = ?,
                        @at2F_status = ?,
                        @at2F_value = ?,
                        @tfB_status = ?,
                        @tfB_value = ?,
                        @tfD_status = ?,
                        @tfD_value = ?,
                        @tfF_status = ?,
                        @tfF_value = ?,
                        @ldB_status = ?,
                        @ldB_value = ?,
                        @ldD_status = ?,
                        @ldD_value = ?,
                        @ldF_status = ?,
                        @ldF_value = ?',
                            [
                                7,
                                $idLaporan,
                                $keterangan,
                                $user_input,
                                $hasilCheck['bz1BD']['status'] ?? null,
                                $hasilCheck['bz1BD']['value'] ?? null,
                                $hasilCheck['bz1DD']['status'] ?? null,
                                $hasilCheck['bz1DD']['value'] ?? null,
                                $hasilCheck['bz1FD']['status'] ?? null,
                                $hasilCheck['bz1FD']['value'] ?? null,
                                $hasilCheck['bz2BD']['status'] ?? null,
                                $hasilCheck['bz2BD']['value'] ?? null,
                                $hasilCheck['bz2DD']['status'] ?? null,
                                $hasilCheck['bz2DD']['value'] ?? null,
                                $hasilCheck['bz2FD']['status'] ?? null,
                                $hasilCheck['bz2FD']['value'] ?? null,
                                $hasilCheck['bz3BD']['status'] ?? null,
                                $hasilCheck['bz3BD']['value'] ?? null,
                                $hasilCheck['bz3DD']['status'] ?? null,
                                $hasilCheck['bz3DD']['value'] ?? null,
                                $hasilCheck['bz3FD']['status'] ?? null,
                                $hasilCheck['bz3FD']['value'] ?? null,
                                $hasilCheck['bz4BD']['status'] ?? null,
                                $hasilCheck['bz4BD']['value'] ?? null,
                                $hasilCheck['bz4DD']['status'] ?? null,
                                $hasilCheck['bz4DD']['value'] ?? null,
                                $hasilCheck['bz4FD']['status'] ?? null,
                                $hasilCheck['bz4FD']['value'] ?? null,
                                $hasilCheck['bz5BD']['status'] ?? null,
                                $hasilCheck['bz5BD']['value'] ?? null,
                                $hasilCheck['bz5DD']['status'] ?? null,
                                $hasilCheck['bz5DD']['value'] ?? null,
                                $hasilCheck['bz5FD']['status'] ?? null,
                                $hasilCheck['bz5FD']['value'] ?? null,
                                $hasilCheck['bz6BD']['status'] ?? null,
                                $hasilCheck['bz6BD']['value'] ?? null,
                                $hasilCheck['bz6DD']['status'] ?? null,
                                $hasilCheck['bz6DD']['value'] ?? null,
                                $hasilCheck['bz6FD']['status'] ?? null,
                                $hasilCheck['bz6FD']['value'] ?? null,
                                $hasilCheck['scBD']['status'] ?? null,
                                $hasilCheck['scBD']['value'] ?? null,
                                $hasilCheck['scDD']['status'] ?? null,
                                $hasilCheck['scDD']['value'] ?? null,
                                $hasilCheck['scFD']['status'] ?? null,
                                $hasilCheck['scFD']['value'] ?? null,
                                $hasilCheck['mpBD']['status'] ?? null,
                                $hasilCheck['mpBD']['value'] ?? null,
                                $hasilCheck['mpDD']['status'] ?? null,
                                $hasilCheck['mpDD']['value'] ?? null,
                                $hasilCheck['mpFD']['status'] ?? null,
                                $hasilCheck['mpFD']['value'] ?? null,
                                $hasilCheck['ad1BD']['status'] ?? null,
                                $hasilCheck['ad1BD']['value'] ?? null,
                                $hasilCheck['ad1DD']['status'] ?? null,
                                $hasilCheck['ad1DD']['value'] ?? null,
                                $hasilCheck['ad1FD']['status'] ?? null,
                                $hasilCheck['ad1FD']['value'] ?? null,
                                $hasilCheck['ad2BD']['status'] ?? null,
                                $hasilCheck['ad2BD']['value'] ?? null,
                                $hasilCheck['ad2DD']['status'] ?? null,
                                $hasilCheck['ad2DD']['value'] ?? null,
                                $hasilCheck['ad2FD']['status'] ?? null,
                                $hasilCheck['ad2FD']['value'] ?? null,
                                $hasilCheck['wpheBD']['status'] ?? null,
                                $hasilCheck['wpheBD']['value'] ?? null,
                                $hasilCheck['wpheDD']['status'] ?? null,
                                $hasilCheck['wpheDD']['value'] ?? null,
                                $hasilCheck['wpheFD']['status'] ?? null,
                                $hasilCheck['wpheFD']['value'] ?? null,
                                $hasilCheck['ipheBD']['status'] ?? null,
                                $hasilCheck['ipheBD']['value'] ?? null,
                                $hasilCheck['ipheDD']['status'] ?? null,
                                $hasilCheck['ipheDD']['value'] ?? null,
                                $hasilCheck['ipheFD']['status'] ?? null,
                                $hasilCheck['ipheFD']['value'] ?? null,
                                $hasilCheck['mtBD']['status'] ?? null,
                                $hasilCheck['mtBD']['value'] ?? null,
                                $hasilCheck['mtDD']['status'] ?? null,
                                $hasilCheck['mtDD']['value'] ?? null,
                                $hasilCheck['mtFD']['status'] ?? null,
                                $hasilCheck['mtFD']['value'] ?? null,
                                $hasilCheck['dz1BD']['status'] ?? null,
                                $hasilCheck['dz1BD']['value'] ?? null,
                                $hasilCheck['dz1DD']['status'] ?? null,
                                $hasilCheck['dz1DD']['value'] ?? null,
                                $hasilCheck['dz1FD']['status'] ?? null,
                                $hasilCheck['dz1FD']['value'] ?? null,
                                $hasilCheck['dz2BD']['status'] ?? null,
                                $hasilCheck['dz2BD']['value'] ?? null,
                                $hasilCheck['dz2DD']['status'] ?? null,
                                $hasilCheck['dz2DD']['value'] ?? null,
                                $hasilCheck['dz2FD']['status'] ?? null,
                                $hasilCheck['dz2FD']['value'] ?? null,
                                $hasilCheck['dz3BD']['status'] ?? null,
                                $hasilCheck['dz3BD']['value'] ?? null,
                                $hasilCheck['dz3DD']['status'] ?? null,
                                $hasilCheck['dz3DD']['value'] ?? null,
                                $hasilCheck['dz3FD']['status'] ?? null,
                                $hasilCheck['dz3FD']['value'] ?? null,
                                $hasilCheck['dz4BD']['status'] ?? null,
                                $hasilCheck['dz4BD']['value'] ?? null,
                                $hasilCheck['dz4DD']['status'] ?? null,
                                $hasilCheck['dz4DD']['value'] ?? null,
                                $hasilCheck['dz4FD']['status'] ?? null,
                                $hasilCheck['dz4FD']['value'] ?? null,
                                $hasilCheck['dz5BD']['status'] ?? null,
                                $hasilCheck['dz5BD']['value'] ?? null,
                                $hasilCheck['dz5DD']['status'] ?? null,
                                $hasilCheck['dz5DD']['value'] ?? null,
                                $hasilCheck['dz5FD']['status'] ?? null,
                                $hasilCheck['dz5FD']['value'] ?? null,
                                $hasilCheck['haoBD']['status'] ?? null,
                                $hasilCheck['haoBD']['value'] ?? null,
                                $hasilCheck['haoDD']['status'] ?? null,
                                $hasilCheck['haoDD']['value'] ?? null,
                                $hasilCheck['haoFD']['status'] ?? null,
                                $hasilCheck['haoFD']['value'] ?? null,
                                $hasilCheck['unitBD']['status'] ?? null,
                                $hasilCheck['unitBD']['value'] ?? null,
                                $hasilCheck['unitDD']['status'] ?? null,
                                $hasilCheck['unitDD']['value'] ?? null,
                                $hasilCheck['unitFD']['status'] ?? null,
                                $hasilCheck['unitFD']['value'] ?? null,
                                $hasilCheck['mp2BD']['status'] ?? null,
                                $hasilCheck['mp2BD']['value'] ?? null,
                                $hasilCheck['mp2DD']['status'] ?? null,
                                $hasilCheck['mp2DD']['value'] ?? null,
                                $hasilCheck['mp2FD']['status'] ?? null,
                                $hasilCheck['mp2FD']['value'] ?? null,
                                $hasilCheck['extBD']['status'] ?? null,
                                $hasilCheck['extBD']['value'] ?? null,
                                $hasilCheck['extDD']['status'] ?? null,
                                $hasilCheck['extDD']['value'] ?? null,
                                $hasilCheck['extFD']['status'] ?? null,
                                $hasilCheck['extFD']['value'] ?? null,
                                $hasilCheck['niprBD']['status'] ?? null,
                                $hasilCheck['niprBD']['value'] ?? null,
                                $hasilCheck['niprDD']['status'] ?? null,
                                $hasilCheck['niprDD']['value'] ?? null,
                                $hasilCheck['niprFD']['status'] ?? null,
                                $hasilCheck['niprFD']['value'] ?? null,
                                $hasilCheck['trBD']['status'] ?? null,
                                $hasilCheck['trBD']['value'] ?? null,
                                $hasilCheck['trDD']['status'] ?? null,
                                $hasilCheck['trDD']['value'] ?? null,
                                $hasilCheck['trFD']['status'] ?? null,
                                $hasilCheck['trFD']['value'] ?? null,
                                $hasilCheck['huBD']['status'] ?? null,
                                $hasilCheck['huBD']['value'] ?? null,
                                $hasilCheck['huDD']['status'] ?? null,
                                $hasilCheck['huDD']['value'] ?? null,
                                $hasilCheck['huFD']['status'] ?? null,
                                $hasilCheck['huFD']['value'] ?? null,
                                $hasilCheck['isuBD']['status'] ?? null,
                                $hasilCheck['isuBD']['value'] ?? null,
                                $hasilCheck['isuDD']['status'] ?? null,
                                $hasilCheck['isuDD']['value'] ?? null,
                                $hasilCheck['isuFD']['status'] ?? null,
                                $hasilCheck['isuFD']['value'] ?? null,
                                $hasilCheck['suBD']['status'] ?? null,
                                $hasilCheck['suBD']['value'] ?? null,
                                $hasilCheck['suDD']['status'] ?? null,
                                $hasilCheck['suDD']['value'] ?? null,
                                $hasilCheck['suFD']['status'] ?? null,
                                $hasilCheck['suFD']['value'] ?? null,
                                $hasilCheck['pauBD']['status'] ?? null,
                                $hasilCheck['pauBD']['value'] ?? null,
                                $hasilCheck['pauDD']['status'] ?? null,
                                $hasilCheck['pauDD']['value'] ?? null,
                                $hasilCheck['pauFD']['status'] ?? null,
                                $hasilCheck['pauFD']['value'] ?? null,
                                $hasilCheck['auBD']['status'] ?? null,
                                $hasilCheck['auBD']['value'] ?? null,
                                $hasilCheck['auDD']['status'] ?? null,
                                $hasilCheck['auDD']['value'] ?? null,
                                $hasilCheck['auFD']['status'] ?? null,
                                $hasilCheck['auFD']['value'] ?? null,
                                $hasilCheck['wgBD']['status'] ?? null,
                                $hasilCheck['wgBD']['value'] ?? null,
                                $hasilCheck['wgDD']['status'] ?? null,
                                $hasilCheck['wgDD']['value'] ?? null,
                                $hasilCheck['wgFD']['status'] ?? null,
                                $hasilCheck['wgFD']['value'] ?? null,
                                $hasilCheck['fewBD']['status'] ?? null,
                                $hasilCheck['fewBD']['value'] ?? null,
                                $hasilCheck['fewDD']['status'] ?? null,
                                $hasilCheck['fewDD']['value'] ?? null,
                                $hasilCheck['fewFD']['status'] ?? null,
                                $hasilCheck['fewFD']['value'] ?? null,
                                $hasilCheck['noyBD']['status'] ?? null,
                                $hasilCheck['noyBD']['value'] ?? null,
                                $hasilCheck['noyDD']['status'] ?? null,
                                $hasilCheck['noyDD']['value'] ?? null,
                                $hasilCheck['noyFD']['status'] ?? null,
                                $hasilCheck['noyFD']['value'] ?? null,
                                $hasilCheck['swBD']['status'] ?? null,
                                $hasilCheck['swBD']['value'] ?? null,
                                $hasilCheck['swDD']['status'] ?? null,
                                $hasilCheck['swDD']['value'] ?? null,
                                $hasilCheck['swFD']['status'] ?? null,
                                $hasilCheck['swFD']['value'] ?? null,
                                $hasilCheck['totrBD']['status'] ?? null,
                                $hasilCheck['totrBD']['value'] ?? null,
                                $hasilCheck['totrDD']['status'] ?? null,
                                $hasilCheck['totrDD']['value'] ?? null,
                                $hasilCheck['totrFD']['status'] ?? null,
                                $hasilCheck['totrFD']['value'] ?? null,
                                $hasilCheck['relaxBD']['status'] ?? null,
                                $hasilCheck['relaxBD']['value'] ?? null,
                                $hasilCheck['relaxDD']['status'] ?? null,
                                $hasilCheck['relaxDD']['value'] ?? null,
                                $hasilCheck['relaxFD']['status'] ?? null,
                                $hasilCheck['relaxFD']['value'] ?? null,
                                $hasilCheck['tp2BD']['status'] ?? null,
                                $hasilCheck['tp2BD']['value'] ?? null,
                                $hasilCheck['tp2DD']['status'] ?? null,
                                $hasilCheck['tp2DD']['value'] ?? null,
                                $hasilCheck['tp2FD']['status'] ?? null,
                                $hasilCheck['tp2FD']['value'] ?? null,
                                $hasilCheck['tp1BD']['status'] ?? null,
                                $hasilCheck['tp1BD']['value'] ?? null,
                                $hasilCheck['tp1DD']['status'] ?? null,
                                $hasilCheck['tp1DD']['value'] ?? null,
                                $hasilCheck['tp1FD']['status'] ?? null,
                                $hasilCheck['tp1FD']['value'] ?? null,
                                $hasilCheck['tp3BD']['status'] ?? null,
                                $hasilCheck['tp3BD']['value'] ?? null,
                                $hasilCheck['tp3DD']['status'] ?? null,
                                $hasilCheck['tp3DD']['value'] ?? null,
                                $hasilCheck['tp3FD']['status'] ?? null,
                                $hasilCheck['tp3FD']['value'] ?? null,
                                $hasilCheck['at1BD']['status'] ?? null,
                                $hasilCheck['at1BD']['value'] ?? null,
                                $hasilCheck['at1DD']['status'] ?? null,
                                $hasilCheck['at1DD']['value'] ?? null,
                                $hasilCheck['at1FD']['status'] ?? null,
                                $hasilCheck['at1FD']['value'] ?? null,
                                $hasilCheck['at2BD']['status'] ?? null,
                                $hasilCheck['at2BD']['value'] ?? null,
                                $hasilCheck['at2DD']['status'] ?? null,
                                $hasilCheck['at2DD']['value'] ?? null,
                                $hasilCheck['at2FD']['status'] ?? null,
                                $hasilCheck['at2FD']['value'] ?? null,
                                $hasilCheck['tfBD']['status'] ?? null,
                                $hasilCheck['tfBD']['value'] ?? null,
                                $hasilCheck['tfDD']['status'] ?? null,
                                $hasilCheck['tfDD']['value'] ?? null,
                                $hasilCheck['tfFD']['status'] ?? null,
                                $hasilCheck['tfFD']['value'] ?? null,
                                $hasilCheck['ldBD']['status'] ?? null,
                                $hasilCheck['ldBD']['value'] ?? null,
                                $hasilCheck['ldDD']['status'] ?? null,
                                $hasilCheck['ldDD']['value'] ?? null,
                                $hasilCheck['ldFD']['status'] ?? null,
                                $hasilCheck['ldFD']['value'] ?? null,
                            ]
                        );

                    return response()->json(['message' => 'Keterangan berhasil diupdate!']);

                case 4:
                    // Simpan
                    // Cek apakah sudah ada keterangan
                    $result = DB::connection('ConnTestQC')
                        ->selectOne(
                            'EXEC SP_4451_VerifikasiSettingMesin 
                                @kode = ?,
                                @idLaporan = ?',
                            [
                                2,
                                $idLaporan,
                            ]
                        );

                    // Jika belum ada keterangan
                    if (!$result || $result->count <= 0) {
                        return response()->json([
                            'error' => 'Lakukan proses simpan keterangan dahulu sebelum verifikasi!'
                        ]);
                    }

                    // Jika sudah ada keterangan, lanjut proses verifikasi
                    DB::connection('ConnExtruder')
                        ->statement(
                            'EXEC SP_4451_GetDataLaporanProduksiExtruder 
                        @kode = ?,
                        @idLaporan = ?,
                        @user_input = ?',
                            [
                                8,
                                $idLaporan,
                                $user_input,
                            ]
                        );

                    return response()->json([
                        'message' => 'Data berhasil diverifikasi!'
                    ]);

                case 5:
                    // batal
                    DB::connection('ConnExtruder')
                        ->statement(
                            'EXEC SP_4451_GetDataLaporanProduksiExtruder 
                        @kode = ?,
                        @idLaporan = ?',
                            [
                                9,
                                $idLaporan,
                            ]
                        );

                    return response()->json(['message' => 'Data berhasil dibatal verifikasi!']);

                case 6:
                    // batal D
                    DB::connection('ConnExtruder')
                        ->statement(
                            'EXEC SP_4451_GetDataLaporanProduksiExtruder 
                        @kode = ?,
                        @idLaporan = ?',
                            [
                                10,
                                $idLaporan,
                            ]
                        );

                    return response()->json(['message' => 'Data berhasil dibatal verifikasi!']);

                default:
                    return response()->json(['error', 'Proses tidak valid']);
            }

        } catch (Exception $e) {
            return response()->json([
                'error' => $e->getMessage()
            ]);
        }
    }

    public function show(Request $request, $id)
    {
        if ($id == 'getDataExt') {
            $tgl_awal = $request->input('tgl_awal');
            $tgl_akhir = $request->input('tgl_akhir');
            $id_lokasi = $request->input('id_lokasi');

            if ($id_lokasi == 3) {
                // dd($tgl_awal, $tgl_akhir, $id_lokasi);
                $results = DB::connection('ConnExtruder')
                    ->select('EXEC SP_4451_LaporanProduksiLohia @Kode = ?, @tgl_awal = ?, @tgl_akhir = ?, @lokasi = ?', [5, $tgl_awal, $tgl_akhir, $id_lokasi]);
                // dd($results);
                $response = [];
                foreach ($results as $row) {
                    $response[] = [
                        'tanggal' => Carbon::parse($row->tanggal)->format('m/d/Y'),
                        'tanggal_raw' => Carbon::parse($row->tanggal)->format('Y-m-d'),
                        'idLaporan' => trim($row->idLaporan),
                        'shiftValue' => trim($row->shiftValue),
                        // 'tanggal' => trim($row->tanggal),
                        'spek_mesin' => trim($row->spek_mesin),
                        'spek_benang' => trim($row->spek_benang),
                        'userInput' => trim($row->user_input),
                        'userVerified' => trim($row->userVerified),
                        'userACCSPV' => trim($row->userACCSPV),
                        'bahanPP' => $row->bahanPP ?? '',
                    ];
                }
                // dd($response);
                return datatables($response)->make(true);
            } else {
                $results = DB::connection('ConnExtruder')
                    ->select('EXEC SP_4451_GetDataLaporanProduksiExtruder @Kode = ?, @tgl_awal = ?, @tgl_akhir = ?, @lokasi = ?', [4, $tgl_awal, $tgl_akhir, $id_lokasi]);
                $response = [];
                foreach ($results as $row) {
                    $response[] = [
                        'tanggal' => Carbon::parse($row->tanggal)->format('m/d/Y'),
                        'tanggal_raw' => Carbon::parse($row->tanggal)->format('Y-m-d'),
                        'idLaporan' => trim($row->idLaporan),
                        'shiftValue' => trim($row->shiftValue),
                        // 'tanggal' => trim($row->tanggal),
                        'spek_mesin' => trim($row->spek_mesin),
                        'spek_benang' => trim($row->spek_benang),
                        'userInput' => trim($row->userInput),
                        'userVerified' => trim($row->userVerified),
                        'userACCSPV' => trim($row->userACCSPV),
                        'bahanPP' => $row->bahanPP ?? '',
                    ];
                }
                // dd($response);
                return datatables($response)->make(true);
            }
        } else if ($id == 'getDataPrint') {
            $idLaporan = $request->input('idLaporan');
            $results = DB::connection('ConnExtruder')
                ->table('LaporanProduksiExtruder')
                ->where('idLaporan', $idLaporan)
                ->select('*')
                ->get();

            $results2 = DB::connection('ConnTestQC')
                ->table('Verifikasi_SettingMesin')
                ->where('idLaporan', $idLaporan)
                ->select('*')
                ->get();
            if ($results) {
                $userInput = trim($results[0]->userInput);
                $userVerified = trim($results[0]->userVerified) ?? '';
            }
            // dd($results2);
            $ttdRaw = DB::connection('ConnEDP')
                ->select('EXEC SP_4451_EDP_MaintenanceTTDUser @XKode = ?, @XNomorUser = ?', [2, $userVerified]);
            $ttd = null;
            if (!empty($ttdRaw)) {
                $row = $ttdRaw[0]; // ttd pasti 1 baris
                $ttd = [
                    'NamaUser' => $row->NamaUser,
                    'FotoTtd' => trim($row->FotoTtd) ?? '',
                ];
            }

            // dd($ttd);
            if (!empty($results)) {
                return response()->json([
                    'status' => 'ada',
                    'ttd' => $ttd,
                    'data' => $results,
                    'data2' => $results2
                ]);
            } else {
                return response()->json([
                    'status' => 'tidakAda',
                    'ttd' => [],
                    'data' => [],
                    'data2' => []
                ]);

            }
        } else if ($id == 'getPrintLaporanL') {
            $idLaporan = $request->input('idLaporan');
            $results = DB::connection('ConnExtruder')
                ->table('LaporanProduksiLohia')
                ->where('idLaporan', $idLaporan)
                ->select('*')
                ->get();
            $results2 = DB::connection('ConnTestQC')
                ->table('Verifikasi_SettingMesinLohia')
                ->where('idLaporan', $idLaporan)
                ->select('*')
                ->get();
            if ($results) {
                $user_input = trim($results[0]->user_input);
            }

            $ttdRaw = DB::connection('ConnEDP')
                ->select('EXEC SP_4451_EDP_MaintenanceTTDUser @XKode = ?, @XNomorUser = ?', [2, $user_input]);
            $ttd = null;
            if (!empty($ttdRaw)) {
                $row = $ttdRaw[0]; // ttd pasti 1 baris
                $ttd = [
                    'NamaUser' => $row->NamaUser,
                    'FotoTtd' => trim($row->FotoTtd),
                ];
            }
            if (!empty($results)) {
                return response()->json([
                    'status' => 'ada',
                    'ttd' => $ttd,
                    'data' => $results,
                    'data2' => $results2
                ]);
            } else {
                return response()->json([
                    'status' => 'tidakAda',
                    'ttd' => [],
                    'data' => [],
                    'data2' => []
                ]);

            }

        }
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}
